---
title: "Proyecto Bariatría"
subtitle: "Parte 1: Plan de análisis y análisis descriptivos"
author: 
  - "nombre, autor principal"
  - "Javier Mancilla Galindo, supervisor"
  - "Ashuin Kammar García, supervisor"
date: today
execute: 
  echo: true
  warning: false
format:
  html:
    toc: true
    toc_float: true
    embed-resources: true
  pdf: 
    toc: true
    documentclass: scrartcl
editor: visual
---

\pagebreak

# Setup

```{r}
#| include: false  

# Create directories for sub-folders  
inputfolder <- "../data/raw"
psfolder <- "../data/processed"
tempfolder <- "../data/temp"
figfolder <- "../results/output_figures"
tabfolder <- "../results/output_tables"

dir.create(inputfolder, showWarnings = FALSE)
dir.create(psfolder, showWarnings = FALSE)
dir.create(tempfolder, showWarnings = FALSE)
dir.create(figfolder, showWarnings = FALSE)
dir.create(tabfolder, showWarnings = FALSE)
```

## Packages used

```{r}
#| echo: true 

if (!require("pacman", quietly = TRUE)) {
  install.packages("pacman")
}

pacman::p_load(
  tidyverse,  # Used for basic data handling and visualization.
  table1,     # Used to add labels to variables.
  gt,         # Used to print html tables.  
  report      # Used to cite packages used in this session.   
)
```

\pagebreak

## Session and package dependencies

```{r}
#| echo: false  

# remove clutter
session <- sessionInfo()
session$BLAS <- NULL
session$LAPACK <- NULL
session$loadedOnly <- NULL
# write log file
writeLines(
  capture.output(print(session, locale = FALSE)),
  paste0("sessions/",lubridate::today(), "_session_Part_1.txt")
)                                   # Change name to match your new .qmd file.

session
```

Load data  
```{r}
#| echo: true  
load(
  paste0(psfolder,"/datos_procesados.RData")
  )
```

## Plan de análisis 


## Análisis descriptivos 

```{r}
str(data)
```


# Package References 

```{r}
#| include: false
report::cite_packages(session)
```

Copia y pega el resultado anterior aquí. 

```{r}
#| include: false

# Run this chunk if you wish to clear your environment and unload packages.

pacman::p_unload(negate = TRUE)

rm(list = ls())
```